// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__PEN_H__
#define __BITPROTO__PEN_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef uint8_t Color; // 3bit

#define COLOR_UNKNOWN 0
#define COLOR_RED 1
#define COLOR_BLUE 2
#define COLOR_GREEN 3

typedef int64_t Timestamp; // 64bit

// Number of bytes to encode struct Pen
#define BYTES_LENGTH_PEN 9

struct Pen {
    Color color; // 3bit
    Timestamp produced_at; // 64bit
};

// Encode struct Pen to given buffer s.
int EncodePen(struct Pen *m, unsigned char *s);
// Decode struct Pen from given buffer s.
int DecodePen(struct Pen *m, unsigned char *s);
// Format struct Pen to a json format string.
int JsonPen(struct Pen *m, char *s);

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPen(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPen(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif