// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__TEST_H__
#define __BITPROTO__TEST_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef uint8_t Color; // 3bit

#define COLOR_UNKNOWN 0
#define COLOR_RED 1
#define COLOR_BLUE 2
#define COLOR_GREEN 3

typedef int64_t Timestamp; // 64bit

typedef int8_t Dupa; // 8bit

// Number of bytes to encode struct Shit
#define BYTES_LENGTH_SHIT 14

struct Shit {
    bool jeden; // 1bit
    unsigned char array[8]; // 64bit
    uint64_t ptr; // 41bit
};

// Number of bytes to encode struct Pen
#define BYTES_LENGTH_PEN 23

struct Pen {
    Color color; // 3bit
    Timestamp produced_at; // 64bit
    Dupa dupa; // 8bit
    struct Shit shit; // 106bit
};

// Encode struct Shit to given buffer s.
int EncodeShit(struct Shit *m, unsigned char *s);
// Decode struct Shit from given buffer s.
int DecodeShit(struct Shit *m, unsigned char *s);
// Format struct Shit to a json format string.
int JsonShit(struct Shit *m, char *s);

// Encode struct Pen to given buffer s.
int EncodePen(struct Pen *m, unsigned char *s);
// Decode struct Pen from given buffer s.
int DecodePen(struct Pen *m, unsigned char *s);
// Format struct Pen to a json format string.
int JsonPen(struct Pen *m, char *s);

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessDupa(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatDupa(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessShit(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatShit(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPen(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPen(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif