// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "proto_bp.h"

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64, sizeof(int64_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64, sizeof(int64_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitPen(struct Pen *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->color), BpEnum(3, sizeof(Color)), "color");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->produced_at), BpAlias(64, sizeof(Timestamp), BpXXXProcessTimestamp, BpXXXJsonFormatTimestamp, BP_TYPE_INT), "produced_at");
}

void BpXXXProcessPen(void *data, struct BpProcessorContext *ctx) {
    struct Pen *m = (struct Pen *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPen(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 67, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPen(void *data, struct BpJsonFormatContext *ctx) {
    struct Pen *m = (struct Pen *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitPen(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 67, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePen(struct Pen *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPen((void *)m, &ctx);
    return 0;
}

int DecodePen(struct Pen *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPen((void *)m, &ctx);
    return 0;
}

int JsonPen(struct Pen *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPen((void *)m, &ctx);
    return ctx.n;
}