@startuml ss
    Client -> Server: Sends client public key
    Server->Client: Sends server public key
    ...On both sites shared secret is being calculated...
    Client->Server: Client plain challange message
    Server->Client: Server sends encrypted challange message
    ...On client side, decrypts challenge message...
    ...and compares it to previous one...
    Client->Server: Start App
    ...Application is running, client sends messages...
    ...to server and server responds...
    Client->Server: Terminate Connection
@enduml