// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "messaging_bp.h"

void BpXXXProcessArrayInitializeComm1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayInitializeComm1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitInitializeComm(struct InitializeComm *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->public_key), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayInitializeComm1, BpXXXJsonFormatArrayInitializeComm1), "public_key");
}

void BpXXXProcessInitializeComm(void *data, struct BpProcessorContext *ctx) {
    struct InitializeComm *m = (struct InitializeComm *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitInitializeComm(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatInitializeComm(void *data, struct BpJsonFormatContext *ctx) {
    struct InitializeComm *m = (struct InitializeComm *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitInitializeComm(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeInitializeComm(struct InitializeComm *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessInitializeComm((void *)m, &ctx);
    return 0;
}

int DecodeInitializeComm(struct InitializeComm *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessInitializeComm((void *)m, &ctx);
    return 0;
}

int JsonInitializeComm(struct InitializeComm *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatInitializeComm((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayInitializeCommRsp1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayInitializeCommRsp1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitInitializeCommRsp(struct InitializeCommRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->public_key), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayInitializeCommRsp1, BpXXXJsonFormatArrayInitializeCommRsp1), "public_key");
}

void BpXXXProcessInitializeCommRsp(void *data, struct BpProcessorContext *ctx) {
    struct InitializeCommRsp *m = (struct InitializeCommRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitInitializeCommRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatInitializeCommRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct InitializeCommRsp *m = (struct InitializeCommRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitInitializeCommRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeInitializeCommRsp(struct InitializeCommRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessInitializeCommRsp((void *)m, &ctx);
    return 0;
}

int DecodeInitializeCommRsp(struct InitializeCommRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessInitializeCommRsp((void *)m, &ctx);
    return 0;
}

int JsonInitializeCommRsp(struct InitializeCommRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatInitializeCommRsp((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayChallange1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayChallange1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitChallange(struct Challange *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->challange_buffer), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayChallange1, BpXXXJsonFormatArrayChallange1), "challange_buffer");
}

void BpXXXProcessChallange(void *data, struct BpProcessorContext *ctx) {
    struct Challange *m = (struct Challange *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitChallange(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatChallange(void *data, struct BpJsonFormatContext *ctx) {
    struct Challange *m = (struct Challange *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitChallange(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeChallange(struct Challange *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessChallange((void *)m, &ctx);
    return 0;
}

int DecodeChallange(struct Challange *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessChallange((void *)m, &ctx);
    return 0;
}

int JsonChallange(struct Challange *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatChallange((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayChallangeRsp1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayChallangeRsp2(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayChallangeRsp3(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayChallangeRsp1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayChallangeRsp2(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayChallangeRsp3(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitChallangeRsp(struct ChallangeRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->challange_buffer), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayChallangeRsp1, BpXXXJsonFormatArrayChallangeRsp1), "challange_buffer");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->initialization_vector), BpArray(96, 12 * sizeof(uint8_t), BpXXXProcessArrayChallangeRsp2, BpXXXJsonFormatArrayChallangeRsp2), "initialization_vector");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->tag), BpArray(128, 16 * sizeof(uint8_t), BpXXXProcessArrayChallangeRsp3, BpXXXJsonFormatArrayChallangeRsp3), "tag");
}

void BpXXXProcessChallangeRsp(void *data, struct BpProcessorContext *ctx) {
    struct ChallangeRsp *m = (struct ChallangeRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitChallangeRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 480, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatChallangeRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct ChallangeRsp *m = (struct ChallangeRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitChallangeRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 480, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeChallangeRsp(struct ChallangeRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessChallangeRsp((void *)m, &ctx);
    return 0;
}

int DecodeChallangeRsp(struct ChallangeRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessChallangeRsp((void *)m, &ctx);
    return 0;
}

int JsonChallangeRsp(struct ChallangeRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatChallangeRsp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitHandshakeFinished(struct HandshakeFinished *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->ack), BpBool(), "ack");
}

void BpXXXProcessHandshakeFinished(void *data, struct BpProcessorContext *ctx) {
    struct HandshakeFinished *m = (struct HandshakeFinished *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitHandshakeFinished(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatHandshakeFinished(void *data, struct BpJsonFormatContext *ctx) {
    struct HandshakeFinished *m = (struct HandshakeFinished *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitHandshakeFinished(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeHandshakeFinished(struct HandshakeFinished *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessHandshakeFinished((void *)m, &ctx);
    return 0;
}

int DecodeHandshakeFinished(struct HandshakeFinished *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessHandshakeFinished((void *)m, &ctx);
    return 0;
}

int JsonHandshakeFinished(struct HandshakeFinished *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatHandshakeFinished((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitHandshakeFinishedRsp(struct HandshakeFinishedRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->ack), BpBool(), "ack");
}

void BpXXXProcessHandshakeFinishedRsp(void *data, struct BpProcessorContext *ctx) {
    struct HandshakeFinishedRsp *m = (struct HandshakeFinishedRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitHandshakeFinishedRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatHandshakeFinishedRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct HandshakeFinishedRsp *m = (struct HandshakeFinishedRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitHandshakeFinishedRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeHandshakeFinishedRsp(struct HandshakeFinishedRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessHandshakeFinishedRsp((void *)m, &ctx);
    return 0;
}

int DecodeHandshakeFinishedRsp(struct HandshakeFinishedRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessHandshakeFinishedRsp((void *)m, &ctx);
    return 0;
}

int JsonHandshakeFinishedRsp(struct HandshakeFinishedRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatHandshakeFinishedRsp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitMessages(struct Messages *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->id), BpEnum(8, sizeof(MessageId)), "id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->init_comm), BpMessage(256, sizeof(struct InitializeComm), BpXXXProcessInitializeComm, BpXXXJsonFormatInitializeComm), "init_comm");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->challange), BpMessage(256, sizeof(struct Challange), BpXXXProcessChallange, BpXXXJsonFormatChallange), "challange");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->handshake_finished), BpMessage(1, sizeof(struct HandshakeFinished), BpXXXProcessHandshakeFinished, BpXXXJsonFormatHandshakeFinished), "handshake_finished");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->start_app), BpBool(), "start_app");
}

void BpXXXProcessMessages(void *data, struct BpProcessorContext *ctx) {
    struct Messages *m = (struct Messages *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitMessages(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 522, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatMessages(void *data, struct BpJsonFormatContext *ctx) {
    struct Messages *m = (struct Messages *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitMessages(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 522, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeMessages(struct Messages *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessMessages((void *)m, &ctx);
    return 0;
}

int DecodeMessages(struct Messages *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessMessages((void *)m, &ctx);
    return 0;
}

int JsonMessages(struct Messages *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatMessages((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitResponses(struct Responses *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->id), BpEnum(8, sizeof(MessageId)), "id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->init_comm), BpMessage(256, sizeof(struct InitializeCommRsp), BpXXXProcessInitializeCommRsp, BpXXXJsonFormatInitializeCommRsp), "init_comm");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->challange), BpMessage(480, sizeof(struct ChallangeRsp), BpXXXProcessChallangeRsp, BpXXXJsonFormatChallangeRsp), "challange");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->handshake_finished), BpMessage(1, sizeof(struct HandshakeFinishedRsp), BpXXXProcessHandshakeFinishedRsp, BpXXXJsonFormatHandshakeFinishedRsp), "handshake_finished");
}

void BpXXXProcessResponses(void *data, struct BpProcessorContext *ctx) {
    struct Responses *m = (struct Responses *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitResponses(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 745, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatResponses(void *data, struct BpJsonFormatContext *ctx) {
    struct Responses *m = (struct Responses *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitResponses(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 745, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeResponses(struct Responses *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessResponses((void *)m, &ctx);
    return 0;
}

int DecodeResponses(struct Responses *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessResponses((void *)m, &ctx);
    return 0;
}

int JsonResponses(struct Responses *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatResponses((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitGenerate(struct Generate *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->generate), BpBool(), "generate");
}

void BpXXXProcessGenerate(void *data, struct BpProcessorContext *ctx) {
    struct Generate *m = (struct Generate *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitGenerate(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatGenerate(void *data, struct BpJsonFormatContext *ctx) {
    struct Generate *m = (struct Generate *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitGenerate(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeGenerate(struct Generate *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessGenerate((void *)m, &ctx);
    return 0;
}

int DecodeGenerate(struct Generate *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessGenerate((void *)m, &ctx);
    return 0;
}

int JsonGenerate(struct Generate *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatGenerate((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayGenerateRsp1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayGenerateRsp2(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayGenerateRsp3(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayGenerateRsp1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayGenerateRsp2(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayGenerateRsp3(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitGenerateRsp(struct GenerateRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->generated_password), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayGenerateRsp1, BpXXXJsonFormatArrayGenerateRsp1), "generated_password");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->initialization_vector), BpArray(96, 12 * sizeof(uint8_t), BpXXXProcessArrayGenerateRsp2, BpXXXJsonFormatArrayGenerateRsp2), "initialization_vector");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->tag), BpArray(128, 16 * sizeof(uint8_t), BpXXXProcessArrayGenerateRsp3, BpXXXJsonFormatArrayGenerateRsp3), "tag");
}

void BpXXXProcessGenerateRsp(void *data, struct BpProcessorContext *ctx) {
    struct GenerateRsp *m = (struct GenerateRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitGenerateRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 480, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatGenerateRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct GenerateRsp *m = (struct GenerateRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitGenerateRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 480, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeGenerateRsp(struct GenerateRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessGenerateRsp((void *)m, &ctx);
    return 0;
}

int DecodeGenerateRsp(struct GenerateRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessGenerateRsp((void *)m, &ctx);
    return 0;
}

int JsonGenerateRsp(struct GenerateRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatGenerateRsp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitReadEntry(struct ReadEntry *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->index), BpUint(8, sizeof(uint8_t)), "index");
}

void BpXXXProcessReadEntry(void *data, struct BpProcessorContext *ctx) {
    struct ReadEntry *m = (struct ReadEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitReadEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatReadEntry(void *data, struct BpJsonFormatContext *ctx) {
    struct ReadEntry *m = (struct ReadEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitReadEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeReadEntry(struct ReadEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessReadEntry((void *)m, &ctx);
    return 0;
}

int DecodeReadEntry(struct ReadEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessReadEntry((void *)m, &ctx);
    return 0;
}

int JsonReadEntry(struct ReadEntry *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatReadEntry((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayReadEntryRsp1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayReadEntryRsp2(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayReadEntryRsp1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayReadEntryRsp2(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitReadEntryRsp(struct ReadEntryRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->info), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayReadEntryRsp1, BpXXXJsonFormatArrayReadEntryRsp1), "info");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->wrapped_password), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayReadEntryRsp2, BpXXXJsonFormatArrayReadEntryRsp2), "wrapped_password");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->password_length), BpUint(8, sizeof(uint8_t)), "password_length");
}

void BpXXXProcessReadEntryRsp(void *data, struct BpProcessorContext *ctx) {
    struct ReadEntryRsp *m = (struct ReadEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitReadEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 520, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatReadEntryRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct ReadEntryRsp *m = (struct ReadEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitReadEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 520, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeReadEntryRsp(struct ReadEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessReadEntryRsp((void *)m, &ctx);
    return 0;
}

int DecodeReadEntryRsp(struct ReadEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessReadEntryRsp((void *)m, &ctx);
    return 0;
}

int JsonReadEntryRsp(struct ReadEntryRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatReadEntryRsp((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayAddEntry1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayAddEntry2(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayAddEntry3(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayAddEntry4(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayAddEntry5(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXProcessArrayAddEntry6(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry2(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry3(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry4(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry5(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 16, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntry6(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 12, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitAddEntry(struct AddEntry *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->info), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayAddEntry1, BpXXXJsonFormatArrayAddEntry1), "info");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->kek), BpArray(128, 16 * sizeof(uint8_t), BpXXXProcessArrayAddEntry2, BpXXXJsonFormatArrayAddEntry2), "kek");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->tag_kek), BpArray(128, 16 * sizeof(uint8_t), BpXXXProcessArrayAddEntry3, BpXXXJsonFormatArrayAddEntry3), "tag_kek");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->wrapped_password), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayAddEntry4, BpXXXJsonFormatArrayAddEntry4), "wrapped_password");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->tag_pass), BpArray(128, 16 * sizeof(uint8_t), BpXXXProcessArrayAddEntry5, BpXXXJsonFormatArrayAddEntry5), "tag_pass");
    fds[5] = BpMessageFieldDescriptor((void *)&(m->initialization_vector), BpArray(96, 12 * sizeof(uint8_t), BpXXXProcessArrayAddEntry6, BpXXXJsonFormatArrayAddEntry6), "initialization_vector");
    fds[6] = BpMessageFieldDescriptor((void *)&(m->password_length), BpUint(8, sizeof(uint8_t)), "password_length");
}

void BpXXXProcessAddEntry(void *data, struct BpProcessorContext *ctx) {
    struct AddEntry *m = (struct AddEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitAddEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 1000, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatAddEntry(void *data, struct BpJsonFormatContext *ctx) {
    struct AddEntry *m = (struct AddEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[7];
    BpFieldDescriptorsInitAddEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 7, 1000, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeAddEntry(struct AddEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessAddEntry((void *)m, &ctx);
    return 0;
}

int DecodeAddEntry(struct AddEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessAddEntry((void *)m, &ctx);
    return 0;
}

int JsonAddEntry(struct AddEntry *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatAddEntry((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayAddEntryRsp2(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAddEntryRsp2(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitAddEntryRsp(struct AddEntryRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->index), BpUint(8, sizeof(uint8_t)), "index");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->info), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayAddEntryRsp2, BpXXXJsonFormatArrayAddEntryRsp2), "info");
}

void BpXXXProcessAddEntryRsp(void *data, struct BpProcessorContext *ctx) {
    struct AddEntryRsp *m = (struct AddEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitAddEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 264, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatAddEntryRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct AddEntryRsp *m = (struct AddEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitAddEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 264, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeAddEntryRsp(struct AddEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessAddEntryRsp((void *)m, &ctx);
    return 0;
}

int DecodeAddEntryRsp(struct AddEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessAddEntryRsp((void *)m, &ctx);
    return 0;
}

int JsonAddEntryRsp(struct AddEntryRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatAddEntryRsp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitDelEntry(struct DelEntry *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->index), BpUint(8, sizeof(uint8_t)), "index");
}

void BpXXXProcessDelEntry(void *data, struct BpProcessorContext *ctx) {
    struct DelEntry *m = (struct DelEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitDelEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatDelEntry(void *data, struct BpJsonFormatContext *ctx) {
    struct DelEntry *m = (struct DelEntry *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitDelEntry(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 8, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeDelEntry(struct DelEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessDelEntry((void *)m, &ctx);
    return 0;
}

int DecodeDelEntry(struct DelEntry *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessDelEntry((void *)m, &ctx);
    return 0;
}

int JsonDelEntry(struct DelEntry *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatDelEntry((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitDelEntryRsp(struct DelEntryRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->ack), BpBool(), "ack");
}

void BpXXXProcessDelEntryRsp(void *data, struct BpProcessorContext *ctx) {
    struct DelEntryRsp *m = (struct DelEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitDelEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatDelEntryRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct DelEntryRsp *m = (struct DelEntryRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitDelEntryRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 1, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeDelEntryRsp(struct DelEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessDelEntryRsp((void *)m, &ctx);
    return 0;
}

int DecodeDelEntryRsp(struct DelEntryRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessDelEntryRsp((void *)m, &ctx);
    return 0;
}

int JsonDelEntryRsp(struct DelEntryRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatDelEntryRsp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitApp(struct App *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->node_id), BpEnum(8, sizeof(AppNode)), "node_id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->new_entry), BpMessage(1000, sizeof(struct AddEntry), BpXXXProcessAddEntry, BpXXXJsonFormatAddEntry), "new_entry");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->generate), BpMessage(1, sizeof(struct Generate), BpXXXProcessGenerate, BpXXXJsonFormatGenerate), "generate");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->del_entry), BpMessage(8, sizeof(struct DelEntry), BpXXXProcessDelEntry, BpXXXJsonFormatDelEntry), "del_entry");
}

void BpXXXProcessApp(void *data, struct BpProcessorContext *ctx) {
    struct App *m = (struct App *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitApp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 1017, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatApp(void *data, struct BpJsonFormatContext *ctx) {
    struct App *m = (struct App *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitApp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 1017, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeApp(struct App *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessApp((void *)m, &ctx);
    return 0;
}

int DecodeApp(struct App *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessApp((void *)m, &ctx);
    return 0;
}

int JsonApp(struct App *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatApp((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitAppRsp(struct AppRsp *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->node_id), BpEnum(8, sizeof(AppNode)), "node_id");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->new_entry), BpMessage(264, sizeof(struct AddEntryRsp), BpXXXProcessAddEntryRsp, BpXXXJsonFormatAddEntryRsp), "new_entry");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->generate), BpMessage(480, sizeof(struct GenerateRsp), BpXXXProcessGenerateRsp, BpXXXJsonFormatGenerateRsp), "generate");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->del_entry), BpMessage(1, sizeof(struct DelEntryRsp), BpXXXProcessDelEntryRsp, BpXXXJsonFormatDelEntryRsp), "del_entry");
}

void BpXXXProcessAppRsp(void *data, struct BpProcessorContext *ctx) {
    struct AppRsp *m = (struct AppRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitAppRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 753, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatAppRsp(void *data, struct BpJsonFormatContext *ctx) {
    struct AppRsp *m = (struct AppRsp *)(data);
    struct BpMessageFieldDescriptor field_descriptors[4];
    BpFieldDescriptorsInitAppRsp(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 4, 753, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeAppRsp(struct AppRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessAppRsp((void *)m, &ctx);
    return 0;
}

int DecodeAppRsp(struct AppRsp *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessAppRsp((void *)m, &ctx);
    return 0;
}

int JsonAppRsp(struct AppRsp *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatAppRsp((void *)m, &ctx);
    return ctx.n;
}