// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "messaging_bp.h"

void BpXXXProcessArrayAESEncrypt1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 64, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAESEncrypt1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 64, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitAESEncrypt(struct AESEncrypt *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->input), BpArray(512, 64 * sizeof(uint8_t), BpXXXProcessArrayAESEncrypt1, BpXXXJsonFormatArrayAESEncrypt1), "input");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->size), BpUint(16, sizeof(uint16_t)), "size");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->encrypt), BpBool(), "encrypt");
}

void BpXXXProcessAESEncrypt(void *data, struct BpProcessorContext *ctx) {
    struct AESEncrypt *m = (struct AESEncrypt *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitAESEncrypt(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 529, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatAESEncrypt(void *data, struct BpJsonFormatContext *ctx) {
    struct AESEncrypt *m = (struct AESEncrypt *)(data);
    struct BpMessageFieldDescriptor field_descriptors[3];
    BpFieldDescriptorsInitAESEncrypt(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 3, 529, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeAESEncrypt(struct AESEncrypt *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessAESEncrypt((void *)m, &ctx);
    return 0;
}

int DecodeAESEncrypt(struct AESEncrypt *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessAESEncrypt((void *)m, &ctx);
    return 0;
}

int JsonAESEncrypt(struct AESEncrypt *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatAESEncrypt((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayAESResponse1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 64, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayAESResponse1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 64, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitAESResponse(struct AESResponse *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->response), BpArray(512, 64 * sizeof(uint8_t), BpXXXProcessArrayAESResponse1, BpXXXJsonFormatArrayAESResponse1), "response");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->size), BpUint(16, sizeof(uint16_t)), "size");
}

void BpXXXProcessAESResponse(void *data, struct BpProcessorContext *ctx) {
    struct AESResponse *m = (struct AESResponse *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitAESResponse(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 528, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatAESResponse(void *data, struct BpJsonFormatContext *ctx) {
    struct AESResponse *m = (struct AESResponse *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitAESResponse(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 528, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeAESResponse(struct AESResponse *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessAESResponse((void *)m, &ctx);
    return 0;
}

int DecodeAESResponse(struct AESResponse *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessAESResponse((void *)m, &ctx);
    return 0;
}

int JsonAESResponse(struct AESResponse *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatAESResponse((void *)m, &ctx);
    return ctx.n;
}

void BpXXXProcessArrayPublicKeyExchange1(void *data, struct BpProcessorContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpEndecodeArray(&descriptor, ctx, data);
}

void BpXXXJsonFormatArrayPublicKeyExchange1(void *data, struct BpJsonFormatContext *ctx) {
    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, 32, BpUint(8, sizeof(uint8_t)));
    BpJsonFormatArray(&descriptor, ctx, data);
}

void BpFieldDescriptorsInitPublicKeyExchange(struct PublicKeyExchange *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->pub_key), BpArray(256, 32 * sizeof(uint8_t), BpXXXProcessArrayPublicKeyExchange1, BpXXXJsonFormatArrayPublicKeyExchange1), "pub_key");
}

void BpXXXProcessPublicKeyExchange(void *data, struct BpProcessorContext *ctx) {
    struct PublicKeyExchange *m = (struct PublicKeyExchange *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitPublicKeyExchange(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatPublicKeyExchange(void *data, struct BpJsonFormatContext *ctx) {
    struct PublicKeyExchange *m = (struct PublicKeyExchange *)(data);
    struct BpMessageFieldDescriptor field_descriptors[1];
    BpFieldDescriptorsInitPublicKeyExchange(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 1, 256, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodePublicKeyExchange(struct PublicKeyExchange *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessPublicKeyExchange((void *)m, &ctx);
    return 0;
}

int DecodePublicKeyExchange(struct PublicKeyExchange *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessPublicKeyExchange((void *)m, &ctx);
    return 0;
}

int JsonPublicKeyExchange(struct PublicKeyExchange *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatPublicKeyExchange((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitMsg(struct Msg *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->msg), BpEnum(3, sizeof(MesssageType)), "msg");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->res), BpEnum(3, sizeof(MessageResponse)), "res");
}

void BpXXXProcessMsg(void *data, struct BpProcessorContext *ctx) {
    struct Msg *m = (struct Msg *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitMsg(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 6, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatMsg(void *data, struct BpJsonFormatContext *ctx) {
    struct Msg *m = (struct Msg *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitMsg(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 6, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeMsg(struct Msg *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessMsg((void *)m, &ctx);
    return 0;
}

int DecodeMsg(struct Msg *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessMsg((void *)m, &ctx);
    return 0;
}

int JsonMsg(struct Msg *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatMsg((void *)m, &ctx);
    return ctx.n;
}