// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__MESSAGING_H__
#define __BITPROTO__MESSAGING_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

// Number of bytes to encode struct AESEncrypt
#define BYTES_LENGTH_AES_ENCRYPT 67

struct AESEncrypt {
    uint8_t input[64]; // 512bit
    uint16_t size; // 16bit
    bool encrypt; // 1bit
};

// Number of bytes to encode struct AESResponse
#define BYTES_LENGTH_AES_RESPONSE 66

struct AESResponse {
    uint8_t response[64]; // 512bit
    uint16_t size; // 16bit
};

// Number of bytes to encode struct PublicKeyExchange
#define BYTES_LENGTH_PUBLIC_KEY_EXCHANGE 32

struct PublicKeyExchange {
    uint8_t pub_key[32]; // 256bit
};

typedef uint8_t MessageResponse; // 3bit

#define ACK 0
#define NACK 1

typedef uint8_t MesssageType; // 3bit

#define PUBLIC_KEY_ECHANGE 0

// Number of bytes to encode struct Msg
#define BYTES_LENGTH_MSG 1

struct Msg {
    MesssageType msg; // 3bit
    MessageResponse res; // 3bit
};

// Encode struct AESEncrypt to given buffer s.
int EncodeAESEncrypt(struct AESEncrypt *m, unsigned char *s);
// Decode struct AESEncrypt from given buffer s.
int DecodeAESEncrypt(struct AESEncrypt *m, unsigned char *s);
// Format struct AESEncrypt to a json format string.
int JsonAESEncrypt(struct AESEncrypt *m, char *s);

// Encode struct AESResponse to given buffer s.
int EncodeAESResponse(struct AESResponse *m, unsigned char *s);
// Decode struct AESResponse from given buffer s.
int DecodeAESResponse(struct AESResponse *m, unsigned char *s);
// Format struct AESResponse to a json format string.
int JsonAESResponse(struct AESResponse *m, char *s);

// Encode struct PublicKeyExchange to given buffer s.
int EncodePublicKeyExchange(struct PublicKeyExchange *m, unsigned char *s);
// Decode struct PublicKeyExchange from given buffer s.
int DecodePublicKeyExchange(struct PublicKeyExchange *m, unsigned char *s);
// Format struct PublicKeyExchange to a json format string.
int JsonPublicKeyExchange(struct PublicKeyExchange *m, char *s);

// Encode struct Msg to given buffer s.
int EncodeMsg(struct Msg *m, unsigned char *s);
// Decode struct Msg from given buffer s.
int DecodeMsg(struct Msg *m, unsigned char *s);
// Format struct Msg to a json format string.
int JsonMsg(struct Msg *m, char *s);

void BpXXXProcessAESEncrypt(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatAESEncrypt(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessAESResponse(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatAESResponse(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessPublicKeyExchange(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatPublicKeyExchange(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessMsg(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatMsg(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif